In [48]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_fwf("weather.dat")

In [49]:
df2 = df.iloc[:,0:3]
df2.rename(columns={"Dy" : "Day","MxT" : "Max","MnT" : "Min"})  \
   .drop(df2.index[0])  \
   .drop(df.tail(1).index,inplace=True)  \
#    .fillna(method='ffill')  \   
#    .set_index('Day')  \

In [50]:
df2.dtypes

Dy     object
MxT    object
MnT    object
dtype: object

In [52]:
df2.fillna(method='ffill')
df2.set_index('Dy')

      MxT   MnT
Dy
NaN   NaN   NaN
1      88    59
2      79    63
3      77    55
4      77    59
5      90    66
6      81    61
7      73    57
8      75    54
9      86   32*
10     84    64
11     91    59
12     88    73
13     70    59
14     61    59
15     64    55
16     79    59
17     81    57
18     82    52
19     81    61
20     84    57
21     86    59
22     90    64
23     90    68
24     90    77
25     90    72
26    97*    64
27     91    72
28     84    68
29     88    66
30     90    45
mo   82.9  60.5

In [54]:
df.fillna(method='ffill').astype(int)

ValueError: Cannot convert non-finite values (NA or inf) to integer