In [17]:
import pandas as pd
from pandas import DataFrame
%matplotlib inline
df = pd.read_csv('sm3.csv')

In [3]:
df.head(5)

,Unnamed: 0,Event ID,Ack.,Event Type,Event Code,Plant,Asset,Start Time,End Time,Duration,...,Level 3,Level 4,Level 5,Level 4.1,Level 5.1,NERC Performance,FEH Level 1,FEH Level 2,System,Component
0,NaN,EG-0016219746,UNACK,Inverter Degraded,PF200 - Production Degraded,047 - San Diego Inspiration Point,INV04 - INV - 4,11/05/2019 13:00:00,NaN,0d 00:42:19,...,Information Available,Operative,In Service,Partial Performance,Derated - Other,NaN,NaN,NaN,NaN,NaN
1,NaN,EG-0016219661,UNACK,Inverter Degraded,PF200 - Production Degraded,006 - City of San Diego- Point Loma Library,INV01 - INV-1,11/05/2019 12:40:00,NaN,0d 01:02:19,...,Information Available,Operative,In Service,Partial Performance,Derated - Other,NaN,NaN,NaN,NaN,NaN
2,NaN,EG-0016200056,UNACK,Plant Comm Loss,PF400 - Communication Issue,009 - Kings Highway,009 - Kings Highway,11/05/2019 13:10:00,NaN,0d 03:32:19,...,Information Unavailable,Information Unavailable,Information Unavailable,Information Unavailable,Information Unavailable,NaN,NaN,NaN,NaN,NaN
3,NaN,EG-0016217778,UNACK,Inverter Degraded,PF200 - Production Degraded,042 - Stockton East Water District - Low Side...,INV10 - INVERTER 10,11/05/2019 09:15:00,NaN,0d 04:27:19,...,Information Available,Operative,In Service,Partial Performance,Derated - Other,NaN,NaN,NaN,NaN,NaN
4,NaN,EG-0016217624,UNACK,Inverter Degraded,PF200 - Production Degraded,042 - Stockton East Water District - Low Side...,INV07 - INVERTER 7,11/05/2019 09:15:00,NaN,0d 04:27:19,...,Information Available,Operative,In Service,Partial Performance,Derated - Other,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(9603, 28)

In [6]:
df.columns

Index(['Unnamed: 0', 'Event ID', 'Ack.', 'Event Type', 'Event Code', 'Plant',
       'Asset', 'Start Time', 'End Time', 'Duration', 'Energy Loss  (kWh)',
       'Rate Loss  (kWh / h)', 'Work Order', 'Work Order Status',
       'Controllable', 'Responsibility', 'Level 1', 'Level 2', 'Level 3',
       'Level 4', 'Level 5', 'Level 4.1', 'Level 5.1', 'NERC Performance',
       'FEH Level 1', 'FEH Level 2', 'System', 'Component'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9603 entries, 0 to 9602
Data columns (total 28 columns):
Unnamed: 0              0 non-null float64
Event ID                9603 non-null object
Ack.                    9603 non-null object
Event Type              9603 non-null object
Event Code              9603 non-null object
Plant                   9603 non-null object
Asset                   9603 non-null object
Start Time              9603 non-null object
End Time                9540 non-null object
Duration                9603 non-null object
Energy Loss  (kWh)      7531 non-null float64
Rate Loss  (kWh / h)    7531 non-null float64
Work Order              9603 non-null object
Work Order Status       4 non-null object
Controllable            9603 non-null object
Responsibility          9603 non-null object
Level 1                 0 non-null float64
Level 2                 0 non-null float64
Level 3                 9603 non-null object
Level 4                 9603 non-null object
Level 5                 9603 non-null object
Level 4.1               9603 non-null object
Level 5.1               9603 non-null object
NERC Performance        0 non-null float64
FEH Level 1             0 non-null float64
FEH Level 2             0 non-null float64
System                  0 non-null float64
Component               0 non-null float64
dtypes: float64(10), object(18)
memory usage: 2.1+ MB

In [12]:
df["Energy Loss  (kWh)"].fillna(0, inplace = True) 
df["Rate Loss  (kWh / h)"].fillna(0, inplace = True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9603 entries, 0 to 9602
Data columns (total 28 columns):
Unnamed: 0              0 non-null float64
Event ID                9603 non-null object
Ack.                    9603 non-null object
Event Type              9603 non-null object
Event Code              9603 non-null object
Plant                   9603 non-null object
Asset                   9603 non-null object
Start Time              9603 non-null object
End Time                9540 non-null object
Duration                9603 non-null object
Energy Loss  (kWh)      9603 non-null float64
Rate Loss  (kWh / h)    9603 non-null float64
Work Order              9603 non-null object
Work Order Status       4 non-null object
Controllable            9603 non-null object
Responsibility          9603 non-null object
Level 1                 0 non-null float64
Level 2                 0 non-null float64
Level 3                 9603 non-null object
Level 4                 9603 non-null object
Level 5                 9603 non-null object
Level 4.1               9603 non-null object
Level 5.1               9603 non-null object
NERC Performance        0 non-null float64
FEH Level 1             0 non-null float64
FEH Level 2             0 non-null float64
System                  0 non-null float64
Component               0 non-null float64
dtypes: float64(10), object(18)
memory usage: 2.1+ MB

In [14]:
df['Asset'].unique()

array(['INV04 - INV - 4', 'INV01 - INV-1', '009 - Kings Highway',
       'INV10 - INVERTER 10', 'INV07 - INVERTER 7', 'INV01 - INVERTER 1',
       'INV08 - INVERTER 8',
       '042 - Stockton East Water District -  Low Side - Ph.II',
       'INV06 - INVERTER 6', 'INV02 - INVERTER 2', 'INV15 - INVERTER 15',
       'INV03 - INVERTER 3', 'INV05 - INVERTER 5', 'INV09 - INVERTER 9',
       'INV13 - INVERTER 13', 'INV04 - INVERTER 4',
       '041 - Stockton East Water District -  High Side - Ph.I',
       'INV11 - INVERTER 11', 'INV12 - INVERTER 12',
       'INV14 - INVERTER 14', 'INV04 - Inverter No. 4',
       'INV13 - Inverter No 13', '057 - Tucson Lighthouse YMCA',
       'INV06 - PV1-6', 'INV08 - INVERTER - 8', 'INV07 - INVERTER - 7',
       '005 - City of San Diego- Rec Center Mountain View',
       'INV03 - INV-03', '067 - Saddle Brook High School',
       'INV01 - Inverter - 1', 'INV01 - Inverter - 8',
       'INV01 - Inverter - 9', 'INV01 - Inverter - 2',
       'INV01 - Inverter - 7', 'INV01 - Inverter - 6',
       'INV01 - Inverter - 5', 'INV01 - Inverter - 3',
       'INV01 - Inverter - 4', 'PYR01 - Sun',
       'PYR01 - Pyranometer_POA - 165468.Sun2', 'PYR01 - Actual GHI',
       'INV05 - INVERTER - 5', 'PYR01 - Pyranometer_POA - 167615.Sun2',
       'WIND01 - Wind Speed', 'INV02 - INV-2',
       '006 - City of San Diego- Point Loma Library', 'INV03 - INV-3',
       'INV01 - PV1-1', 'INV02 - PV1-2', 'INV02 - INV-02',
       '036 - Pima Minimum Security Annex 1', 'INV01 - INV-01',
       'INV06 - INV-6', 'INV01 - INV-01 ', 'INV02 - INV-04',
       '051 - Tucson Quincie Douglas Park', 'INV04 - INV-04',
       '066 - Saddle Brook Franklin ES',
       '029 - San Diego- Police Central Division Garage',
       'INV13 - Inverter No. 13', 'INV16 - Inverter No. 16',
       'INV17 - Inverter No. 17', 'INV18 - Inverter No. 18',
       'INV15 - Inverter No. 15', 'INV07 - Inverter No. 7',
       'INV12 - Inverter No. 12', 'INV06 - Inverter No. 6',
       'INV14 - Inverter No. 14', 'INV10 - Inverter No. 10',
       'INV08 - Inverter No. 8', 'INV03 - Inverter No. 3',
       'INV11 - Inverter No. 11', 'INV09 - Inverter No. 9',
       'INV04 - INVERTER - 4', '017 - Tracy USD -  Kimball HS',
       'INV03 - INVERTER - 3',
       '053 - City of San Diego-  Park De La Cruz', 'INV03 - INV - 3',
       '018 - City of Paso Robles - Sherwood Park', 'INV04 - INV-4',
       'INV02 - INVERTER - 2', 'INV09 - Inverter No 9',
       'INV05 - Inverter No. 5', 'INV10 - Inverter No 10',
       'INV11 - Inverter No 11', 'INV07 - Inverter No 7',
       'INV04 - Inverter No 4',
       '003 - Templeton USD - Templeton High School',
       'INV03 - Inverter No 3', 'INV01 - Inverter No 1',
       'INV05 - Inverter No 5', 'INV12 - Inverter No 12',
       'INV08 - Inverter No 8', 'INV04 - Inverter 4',
       'INV06 - Inverter No 6', 'INV02 - Inverter No 2',
       '011 - Iron Mountain - Livermore', 'INV02 - Inverter 2',
       '026 - Vail Cienega', 'INV05 - INV-5', 'INV05 - INV-05',
       'INV01 - INV-03',
       '007 - San Diego-Police Station Northern Division',
       '014 - Iron Mountain - Otay Mesa', 'INV01 - Inverter 1',
       'INV01 - INVERTER - 1', 'INV04 - INV-22',
       '030 - Imperial County - Jail-RADF',
       '034 - Pima - Wheeler Taft Abbett Library',
       '025 - Pima - Ellie Towne Flowing Wells Community Center',
       'INV03 - INV-15', '035 - Pima - Eckstrom Columbus Library',
       'INV03 - INV-25', '059 - Tucson Adaptive Rec',
       'INV03 - Inverter 3', 'INV01 - INV - 1', 'INV05 - INV - 5',
       'INV07 - INV - 7', 'INV01 - INV -1',
       '010 - City of San Diego- Rec Center & Pool Tierrasanta',
       'INV03 - INV -3', 'INV02 - INV -2', 'INV06 - INV - 6',
       '047 - San Diego Inspiration Point', 'INV02 - INV - 2',
       'INV01 - PV0-1', 'INV08 - INV-35', 'INV02 - INV-08',
       'INV03 - INV-18', 'INV05 - INV-11', 'INV02 - INV-29',
       'INV03 - INV-05', 'INV01 - INV-16', 'INV06 - INV-06',
       'INV04 - INV-10', 'INV05 - INV-32', 'INV07 - INV-34',
       'INV06 - INV-33', 'INV04 - INV-31', 'INV04 - INV-26',
       'INV02 - INV-24', 'INV03 - INV-30', 'INV06 - INV-21',
       'INV02 - INV-17', 'INV06 - INV-12', 'INV03 - INV-09',
       'INV01 - INV-07', 'INV04 - INV-19', 'INV01 - INV-13',
       '056 - Pima Community County College NW - PCC NW',
       'INV05 - INV-27', 'INV01 - INV-28', 'INV01 - INV-23',
       'INV01 - PV 1-1', 'INV02 - PV 1-2', 'INV03 - PV 1-3',
       'INV05 - PV 1-5', 'INV04 - PV 1-4', 'INV07 - PV 1-7',
       'INV06 - PV 1-6', 'INV01 - INV.2', '008 - Sun Chemical',
       'INV13 - PV 1-13', 'INV07 - Inverter 7', 'INV06 - Inverter 6',
       'INV08 - Inverter 8', '060 - Midland Park - Godwin Elementary',
       'INV05 - Inverter 5', 'INV10 - Inverter 10', 'INV09 - Inverter 9',
       'INV04 - INV -1.4', '016 - Burlington High School -\xa0 Cambridge',
       'INV08 - PV1-8', 'INV11 - INV - 11', 'INV01 - Inverter',
       '061 - Midland Park - Highland Elementary', 'INV08 - INV -1.8',
       'INV08 - INV -2.8', 'INV07 - INV -1.7',
       '033 - Middlesex Community College', 'INV06 - INV -1.6',
       'PYR01 - Pyranometer POA', 'INV12 - INV-12',
       '028 - Tracy USD -  West HS', 'INV02',
       '024 - Pima - Animal Care Center', 'INV07 - PV1-7',
       '001 - Halls Warehouse', '062 - Tucson Golf Links Sports Complex',
       'INV04 - PV1-4', 'INV07 - INV -2.7', 'INV01 - INV -2.1',
       '058 - Tucson Randolph Golf Course', '063 - Midland Park High',
       'INV02 - INV -1.2', 'INV03 - INV -1.3', 'INV13 - INVERTER - 13',
       'INV06 - INVERTER - 6', 'INV12 - INVERTER - 12',
       'INV09 - INVERTER - 9', 'INV10 - INVERTER - 10',
       'INV11 - INVERTER - 11', '027 - San Diego- Mission Valley Library',
       '068 - Saddle Brook Long Memorial ES', 'INV02 - INV-14',
       'INV01 - INV.1', 'INV17 - INV-17', 'INV14 - INV-14',
       '052 - Iron Mountain Somerset', 'INV12 - PV 1-12', 'INV05 - PV1-5',
       '044 - Sisters of Notre Dame - Main Grounds',
       '045 - Sisters of Notre Dame - Lourdes Healthcare',
       'PYR01 - Pyranometer_POA', '043 - Barrette Farms 2',
       'INV16 - INVERTER 16', 'INV17 - INVERTER 17', 'INV05 - INV -1.5',
       '031 - Manchester Community College - North', 'INV01 - INV -1.1',
       'INV05 - INV-20', '040 - Pima Murphy Wilmot Library',
       'INV18 - INV-18', 'INV13 - INV-13', 'INV16 - INV-16',
       'INV11 - INV-11', 'INV15 - INV-15', 'INV10 - INV-10',
       'INV07 - INV-7', 'INV09 - INV-9', 'INV08 - INV-8',
       '021 - San Diego- Police Station Western Division ',
       '064 - Tucson Parks and Recreation Admin Building',
       'INV03 - PV0-3', 'INV02 - PV0-2', 'INV10 - INV - 10',
       'INV15 - INV - 15', 'INV14 - INV - 14', 'INV01 - INV 1',
       'INV02 - INV 2', 'INV05 - INV -2.5', 'INV04 - INV -2.4',
       'INV03 - INV -2.3', '054 - Marana Police Station', 'INV03',
       'INV06 - INV -2.6', 'PYR02 - Pyranometer_POA',
       'PYR03 - Pyranometer_POA',
       '023 - Rialto USD - Linda M.Henry Elementary', 'INV12 - INV - 12',
       '032 - Manchester Community College - East', 'INV02 - INV -2.2',
       'INV08 - PV 1-8', 'INV01 - INV-02', 'INV09 - PV 1-9',
       'INV11 - PV 1-11', 'INV10 - PV 1-10', 'INV01 - INV-04', 'INV01',
       'INV03 - PV1-3', 'INV01 - INV#10', 'INV01 - INV#8',
       'INV01 - INV#7', 'INV01 - INV#4', 'INV01 - INV#3', 'INV01 - INV#6',
       'INV01 - INV#9', 'INV01 - INV#1 ', 'INV01 - INV#2',
       'INV01 - INV#5', '050 - Tucson Freedom Park', 'INV08 - INV - 8',
       '049 - ARFF Atlantic City Airport', 'INV01 - INV-05',
       '002 - Templeton USD - Vineyard ES'], dtype=object)

In [15]:
df['Plant']

array(['047 - San Diego Inspiration Point',
       '006 - City of San Diego- Point Loma Library',
       '009 - Kings Highway',
       '042 - Stockton East Water District -  Low Side - Ph.II',
       '041 - Stockton East Water District -  High Side - Ph.I',
       '017 - Tracy USD -  Kimball HS',
       '003 - Templeton USD - Templeton High School',
       '057 - Tucson Lighthouse YMCA', '063 - Midland Park High',
       '030 - Imperial County - Jail-RADF',
       '005 - City of San Diego- Rec Center Mountain View',
       '067 - Saddle Brook High School',
       '058 - Tucson Randolph Golf Course',
       '027 - San Diego- Mission Valley Library',
       '018 - City of Paso Robles - Sherwood Park',
       '059 - Tucson Adaptive Rec', '048 - Vail Academy',
       '050 - Tucson Freedom Park', '051 - Tucson Quincie Douglas Park',
       '039 - Marana Silverbell District Park',
       '040 - Pima Murphy Wilmot Library',
       '007 - San Diego-Police Station Northern Division',
       '060 - Midland Park - Godwin Elementary',
       '036 - Pima Minimum Security Annex 1',
       '024 - Pima - Animal Care Center', '028 - Tracy USD -  West HS',
       '066 - Saddle Brook Franklin ES',
       '029 - San Diego- Police Central Division Garage',
       '053 - City of San Diego-  Park De La Cruz',
       '004 - SeaWorld Aquatica', '011 - Iron Mountain - Livermore',
       '026 - Vail Cienega', '054 - Marana Police Station',
       '014 - Iron Mountain - Otay Mesa',
       '034 - Pima - Wheeler Taft Abbett Library',
       '056 - Pima Community County College NW - PCC NW',
       '025 - Pima - Ellie Towne Flowing Wells Community Center',
       '035 - Pima - Eckstrom Columbus Library',
       '033 - Middlesex Community College',
       '010 - City of San Diego- Rec Center & Pool Tierrasanta',
       '064 - Tucson Parks and Recreation Admin Building',
       '013 - Iron Mountain - Flanders - San Diego',
       '001 - Halls Warehouse', '008 - Sun Chemical',
       '052 - Iron Mountain Somerset',
       '016 - Burlington High School -\xa0 Cambridge',
       '043 - Barrette Farms 2',
       '031 - Manchester Community College - North',
       '061 - Midland Park - Highland Elementary',
       '068 - Saddle Brook Long Memorial ES',
       '032 - Manchester Community College - East',
       '019 - Bridgeport Wonderland of Ice',
       '062 - Tucson Golf Links Sports Complex',
       '044 - Sisters of Notre Dame - Main Grounds',
       '045 - Sisters of Notre Dame - Lourdes Healthcare',
       '002 - Templeton USD - Vineyard ES',
       '021 - San Diego- Police Station Western Division ',
       '046 - San Diego Mission Trails Regional Park',
       '012 - Iron Mountain - Oakland ',
       '038 - Pima Animal Care Center - 2', '065 - Tucson El Pueblo Park',
       '055 - Marana Town Hall', '037 - Marana Ora Mae Public Pool',
       '023 - Rialto USD - Linda M.Henry Elementary',
       '049 - ARFF Atlantic City Airport'], dtype=object)

In [29]:
pd.pivot_table(df,index=["Plant","Asset"], columns=['Event Type'], values=["Energy Loss  (kWh)"],aggfunc='sum',fill_value=0,margins=True)

                                                                                                  Energy Loss  (kWh)  \
Event Type                                                                                                 Comm Loss
Plant                                            Asset
001 - Halls Warehouse                            001 - Halls Warehouse                                             0
                                                 INV01 - PV 1-1                                                    0
                                                 INV02 - PV 1-2                                                    0
                                                 INV03 - PV 1-3                                                    0
                                                 INV04 - PV 1-4                                                    0
                                                 INV05 - PV 1-5                                                    0
                                                 INV06 - PV 1-6                                                    0
                                                 INV08 - PV 1-8                                                    0
                                                 INV09 - PV 1-9                                                    0
                                                 INV10 - PV 1-10                                                   0
                                                 INV11 - PV 1-11                                                   0
002 - Templeton USD - Vineyard ES                002 - Templeton USD - Vineyard ES                                 0
                                                 INV01 - Inverter No 1                                             0
003 - Templeton USD - Templeton High School      003 - Templeton USD - Templeton High School                       0
                                                 INV01 - Inverter No 1                                             0
                                                 INV02 - Inverter No 2                                             0
                                                 INV03 - Inverter No 3                                             0
                                                 INV04 - Inverter No 4                                             0
                                                 INV05 - Inverter No 5                                             0
                                                 INV06 - Inverter No 6                                             0
                                                 INV07 - Inverter No 7                                             0
                                                 INV08 - Inverter No 8                                             0
                                                 INV09 - Inverter No 9                                             0
                                                 INV10 - Inverter No 10                                            0
                                                 INV11 - Inverter No 11                                            0
                                                 INV12 - Inverter No 12                                            0
                                                 INV13 - Inverter No 13                                            0
004 - SeaWorld Aquatica                          INV01 - INV-1                                                     0
                                                 INV02 - INV-2                                                     0
                                                 INV03 - INV-3                                                     0
...                                                                                                              ...
063 - Midland Park High                          INV06 - PV1-6                                                     0
                                                 INV07 - PV1-7                                                     0
                                                 INV08 - PV1-8                                                     0
064 - Tucson Parks and Recreation Admin Building 064 - Tucson Parks and Recreation Admin Building                  0
                                                 INV01 - PV0-1                                                     0
                                                 INV02 - PV0-2                                                     0
                                                 INV03 - PV0-3                                                     0
                                                 PYR01 - Pyranometer_POA                                           0
065 - Tucson El Pueblo Park                      INV01 - INV-01                                                    0
                                                 INV02 - INV-02                                                    0
                                                 INV03 - INV-03                                                    0
066 - Saddle Brook Franklin ES                   066 - Saddle Brook Franklin ES                                    0
                                                 INV01 - Inverter                                                  0
                                                 PYR01 - Sun                                                       0
067 - Saddle Brook High School                   067 - Saddle Brook High School                                    0
                                                 INV01 - Inverter - 1                                              0
                                                 INV01 - Inverter - 2                                              0
                                                 INV01 - Inverter - 3                                              0
                                                 INV01 - Inverter - 4                                              0
                                                 INV01 - Inverter - 5                                              0
                                                 INV01 - Inverter - 6                                              0
                                                 INV01 - Inverter - 7                                              0
                                                 INV01 - Inverter - 8                                              0
                                                 INV01 - Inverter - 9                                              0
                                                 PYR01 - Sun                                                       0
068 - Saddle Brook Long Memorial ES              068 - Saddle Brook Long Memorial ES                               0
                                                 INV01 - Inverter - 1                                              0
                                                 INV01 - Inverter - 2                                              0
                                                 PYR01 - Sun                                                       0
All                                                                                                                0

                                                                                                                     \
Event Type                                                                                        Down (Plant Down)
Plant                                            Asset
001 - Halls Warehouse                            001 - Halls Warehouse                                      0.00000
                                                 INV01 - PV 1-1                                             0.00000
                                                 INV02 - PV 1-2                                             0.00000
                                                 INV03 - PV 1-3                                             0.00000
                                                 INV04 - PV 1-4                                             0.00000
                                                 INV05 - PV 1-5                                             0.00000
                                                 INV06 - PV 1-6                                             0.00000
                                                 INV08 - PV 1-8                                             0.00000
                                                 INV09 - PV 1-9                                             0.00000
                                                 INV10 - PV 1-10                                            0.00000
                                                 INV11 - PV 1-11                                            0.00000
002 - Templeton USD - Vineyard ES                002 - Templeton USD - Vineyard ES                          0.00000
                                                 INV01 - Inverter No 1                                      0.00000
003 - Templeton USD - Templeton High School      003 - Templeton USD - Templeton High School                0.00000
                                                 INV01 - Inverter No 1                                      0.00000
                                                 INV02 - Inverter No 2                                      0.00000
                                                 INV03 - Inverter No 3                                      0.00000
                                                 INV04 - Inverter No 4                                      0.00000
                                                 INV05 - Inverter No 5                                      0.00000
                                                 INV06 - Inverter No 6                                      0.00000
                                                 INV07 - Inverter No 7                                      0.00000
                                                 INV08 - Inverter No 8                                      0.00000
                                                 INV09 - Inverter No 9                                      0.00000
                                                 INV10 - Inverter No 10                                     0.00000
                                                 INV11 - Inverter No 11                                     0.00000
                                                 INV12 - Inverter No 12                                     0.00000
                                                 INV13 - Inverter No 13                                     0.00000
004 - SeaWorld Aquatica                          INV01 - INV-1                                              0.00000
                                                 INV02 - INV-2                                              0.00000
                                                 INV03 - INV-3                                              0.00000
...                                                                                                             ...
063 - Midland Park High                          INV06 - PV1-6                                              0.00000
                                                 INV07 - PV1-7                                              0.00000
                                                 INV08 - PV1-8                                              0.00000
064 - Tucson Parks and Recreation Admin Building 064 - Tucson Parks and Recreation Admin Building           0.00000
                                                 INV01 - PV0-1                                              0.00000
                                                 INV02 - PV0-2                                              0.00000
                                                 INV03 - PV0-3                                              0.00000
                                                 PYR01 - Pyranometer_POA                                    0.00000
065 - Tucson El Pueblo Park                      INV01 - INV-01                                             0.00000
                                                 INV02 - INV-02                                             0.00000
                                                 INV03 - INV-03                                             0.00000
066 - Saddle Brook Franklin ES                   066 - Saddle Brook Franklin ES                             0.00000
                                                 INV01 - Inverter                                           0.00000
                                                 PYR01 - Sun                                                0.00000
067 - Saddle Brook High School                   067 - Saddle Brook High School                             0.00000
                                                 INV01 - Inverter - 1                                       0.00000
                                                 INV01 - Inverter - 2                                       0.00000
                                                 INV01 - Inverter - 3                                       0.00000
                                                 INV01 - Inverter - 4                                       0.00000
                                                 INV01 - Inverter - 5                                       0.00000
                                                 INV01 - Inverter - 6                                       0.00000
                                                 INV01 - Inverter - 7                                       0.00000
                                                 INV01 - Inverter - 8                                       0.00000
                                                 INV01 - Inverter - 9                                       0.00000
                                                 PYR01 - Sun                                                0.00000
068 - Saddle Brook Long Memorial ES              068 - Saddle Brook Long Memorial ES                        0.00000
                                                 INV01 - Inverter - 1                                       1.95420
                                                 INV01 - Inverter - 2                                       2.34803
                                                 PYR01 - Sun                                                0.00000
All                                                                                                       721.50815

                                                                                                                \
Event Type                                                                                            Inv Down
Plant                                            Asset
001 - Halls Warehouse                            001 - Halls Warehouse                                 0.00000
                                                 INV01 - PV 1-1                                        0.00000
                                                 INV02 - PV 1-2                                        0.00000
                                                 INV03 - PV 1-3                                        0.00000
                                                 INV04 - PV 1-4                                        0.00000
                                                 INV05 - PV 1-5                                        0.00000
                                                 INV06 - PV 1-6                                        0.00000
                                                 INV08 - PV 1-8                                        0.00000
                                                 INV09 - PV 1-9                                        0.00000
                                                 INV10 - PV 1-10                                       0.00000
                                                 INV11 - PV 1-11                                       0.00000
002 - Templeton USD - Vineyard ES                002 - Templeton USD - Vineyard ES                     0.00000
                                                 INV01 - Inverter No 1                                 0.00000
003 - Templeton USD - Templeton High School      003 - Templeton USD - Templeton High School           0.00000
                                                 INV01 - Inverter No 1                                 0.00000
                                                 INV02 - Inverter No 2                                 0.00000
                                                 INV03 - Inverter No 3                                 0.00000
                                                 INV04 - Inverter No 4                                 0.00000
                                                 INV05 - Inverter No 5                                 0.00000
                                                 INV06 - Inverter No 6                                 0.00000
                                                 INV07 - Inverter No 7                                 0.00000
                                                 INV08 - Inverter No 8                                 0.00000
                                                 INV09 - Inverter No 9                                 0.00000
                                                 INV10 - Inverter No 10                                0.00000
                                                 INV11 - Inverter No 11                                0.00000
                                                 INV12 - Inverter No 12                                0.00000
                                                 INV13 - Inverter No 13                                0.00000
004 - SeaWorld Aquatica                          INV01 - INV-1                                         0.00000
                                                 INV02 - INV-2                                         0.00000
                                                 INV03 - INV-3                                         0.00000
...                                                                                                        ...
063 - Midland Park High                          INV06 - PV1-6                                         0.00000
                                                 INV07 - PV1-7                                         0.00000
                                                 INV08 - PV1-8                                         0.00000
064 - Tucson Parks and Recreation Admin Building 064 - Tucson Parks and Recreation Admin Building      0.00000
                                                 INV01 - PV0-1                                         0.00000
                                                 INV02 - PV0-2                                         0.00000
                                                 INV03 - PV0-3                                         0.00000
                                                 PYR01 - Pyranometer_POA                               0.00000
065 - Tucson El Pueblo Park                      INV01 - INV-01                                        0.00000
                                                 INV02 - INV-02                                        0.00000
                                                 INV03 - INV-03                                        0.00000
066 - Saddle Brook Franklin ES                   066 - Saddle Brook Franklin ES                        0.00000
                                                 INV01 - Inverter                                      0.00000